INSERT INTO FRIENDSHIP_STATUS(STATUS_NAME)
VALUES ('unconfirmed');
INSERT INTO FRIENDSHIP_STATUS(STATUS_NAME)
VALUES ('confirmed');

INSERT INTO GENRES(GENRE_NAME)
VALUES ('Комедия');
INSERT INTO GENRES(GENRE_NAME)
VALUES ('Драма');
INSERT INTO GENRES(GENRE_NAME)
VALUES ('Мультфильм');
INSERT INTO GENRES(GENRE_NAME)
VALUES ('Триллер');
INSERT INTO GENRES(GENRE_NAME)
VALUES ('Документальный');
INSERT INTO GENRES(GENRE_NAME)
VALUES ('Боевик');

INSERT INTO MPA(MPA_NAME)
VALUES ('G');
INSERT INTO MPA(MPA_NAME)
VALUES ('PG');
INSERT INTO MPA(MPA_NAME)
VALUES ('PG-13');
INSERT INTO MPA(MPA_NAME)
VALUES ('R');
INSERT INTO MPA(MPA_NAME)
VALUES ('NC-17');


